
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action quitAction1;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action quitAction2;
	private global::Gtk.Action ViewAudioAction;
	private global::Gtk.Action harddiskAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.VPaned vpaned4;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Table table4;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Label label2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Table table1;
	private global::Gtk.ComboBox combobox_input_format;
	private global::Gtk.ComboBox combobox_output_format;
	private global::Gtk.Entry entry_filename;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label7;
	private global::Gtk.Table table2;
	private global::Gtk.Button button3;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Statusbar statusbar1;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.quitAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction1, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.quitAction2 = new global::Gtk.Action ("quitAction2", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction2, null);
		this.ViewAudioAction = new global::Gtk.Action ("ViewAudioAction", global::Mono.Unix.Catalog.GetString ("View Audio"), null, null);
		this.ViewAudioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Audio");
		w1.Add (this.ViewAudioAction, null);
		this.harddiskAction = new global::Gtk.Action ("harddiskAction", global::Mono.Unix.Catalog.GetString ("View Audio Files"), null, "gtk-harddisk");
		this.harddiskAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Audio Files");
		w1.Add (this.harddiskAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("NeoSPeech API GUI");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction1' action='FileAction1'><menuitem name='harddiskAction' action='harddiskAction'/><menuitem name='quitAction2' action='quitAction2'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned4 = new global::Gtk.VPaned ();
		this.vpaned4.CanFocus = true;
		this.vpaned4.Name = "vpaned4";
		this.vpaned4.Position = 91;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.table4.Add (this.fixed6);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed6]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Text To Transform");
		this.table4.Add (this.label2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.label2]));
		w4.XPadding = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.GtkScrolledWindow.Add (this.textview2);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w7.Position = 1;
		this.vpaned4.Add (this.vbox4);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.vpaned4 [this.vbox4]));
		w8.Resize = false;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(6)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.combobox_input_format = global::Gtk.ComboBox.NewText ();
		this.combobox_input_format.AppendText (global::Mono.Unix.Catalog.GetString ("NORMAL"));
		this.combobox_input_format.AppendText (global::Mono.Unix.Catalog.GetString ("SSML"));
		this.combobox_input_format.AppendText (global::Mono.Unix.Catalog.GetString ("HTML"));
		this.combobox_input_format.AppendText (global::Mono.Unix.Catalog.GetString ("EMAIL"));
		this.combobox_input_format.Name = "combobox_input_format";
		this.combobox_input_format.Active = 0;
		this.table1.Add (this.combobox_input_format);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_input_format]));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox_output_format = global::Gtk.ComboBox.NewText ();
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("Default"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("Wav"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("PCM"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("MULAW"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("ALAW"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("ADPCM"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("ASF"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("OGG"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("8BITWAV"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("AWAV"));
		this.combobox_output_format.AppendText (global::Mono.Unix.Catalog.GetString ("MUWAV"));
		this.combobox_output_format.Name = "combobox_output_format";
		this.combobox_output_format.Active = 0;
		this.table1.Add (this.combobox_output_format);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_output_format]));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry_filename = new global::Gtk.Entry ();
		this.entry_filename.CanFocus = true;
		this.entry_filename.Name = "entry_filename";
		this.entry_filename.Text = global::Mono.Unix.Catalog.GetString ("output.wav");
		this.entry_filename.IsEditable = true;
		this.entry_filename.InvisibleChar = '•';
		this.table1.Add (this.entry_filename);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry_filename]));
		w11.LeftAttach = ((uint)(5));
		w11.RightAttach = ((uint)(6));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Input Format");
		this.label3.Justify = ((global::Gtk.Justification)(1));
		this.label3.MaxWidthChars = 12;
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w12.XPadding = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Output Format");
		this.label4.Justify = ((global::Gtk.Justification)(1));
		this.label4.MaxWidthChars = 13;
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Filename");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w14.LeftAttach = ((uint)(4));
		w14.RightAttach = ((uint)(5));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox5.Add (this.table1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.table1]));
		w15.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.BorderWidth = ((uint)(9));
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Create Audio");
		this.table2.Add (this.button3);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.button3]));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.table2.Add (this.fixed4);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed4]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox5.Add (this.table2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.table2]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vpaned4.Add (this.vbox5);
		this.vbox1.Add (this.vpaned4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned4]));
		w20.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 775;
		this.DefaultHeight = 381;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.harddiskAction.Activated += new global::System.EventHandler (this.view_files);
		this.combobox_output_format.Changed += new global::System.EventHandler (this.output_format_changed);
		this.combobox_input_format.Changed += new global::System.EventHandler (this.text_format_changed);
		this.button3.Clicked += new global::System.EventHandler (this.tts_call);
	}
}
