
// This file has been generated by the GUI designer. Do not modify.
namespace neoapi
{
	public partial class audio_files
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.Table table1;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget neoapi.audio_files
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "neoapi.audio_files";
			this.Title = global::Mono.Unix.Catalog.GetString ("audio_files");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child neoapi.audio_files.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 129;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'/></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vpaned1.Add (this.toolbar1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.toolbar1]));
			w2.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			w3.Add (this.table1);
			this.scrolledwindow1.Add (w3);
			this.vpaned1.Add (this.scrolledwindow1);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 692;
			this.DefaultHeight = 379;
			this.Show ();
		}
	}
}
